In [1]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [ ]:
a = np.linspace(1, 10, num=10, dtype=int)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [ ]:
a = np.zeros((3, 3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
a = np.random.randint(1, 10, (5, 5), dtype=int)
print(a)

[[4 4 8 6 1]
 [7 3 5 1 1]
 [6 2 9 5 4]
 [9 9 8 8 6]
 [8 5 7 4 2]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [3]:
a = np.random.random((4, 4))
print("variant 1:", "\n", a)
# or
b = np.random.random_sample((4, 4))
print("variant 2:", "\n", b)

variant 1: 
 [[0.34523234 0.6973255  0.7057649  0.76558766]
 [0.11620244 0.16051538 0.94187864 0.8024083 ]
 [0.43096609 0.1132087  0.646722   0.81986453]
 [0.94550732 0.60003311 0.20862268 0.98600844]]
variant 2: 
 [[0.19366401 0.53407886 0.98477087 0.13679814]
 [0.16705867 0.26648776 0.56994328 0.27845424]
 [0.14793221 0.32967957 0.57503405 0.21742528]
 [0.71567311 0.02526902 0.3458229  0.80768417]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
a = np.random.randint(1, 10, (5), dtype=int)
print("array 1:", "\n", a)
b = np.random.randint(1, 10, (5), dtype=int)
print("array 2:", "\n", b)
print("Addition:", "\n", a + b)
print("Subtraction:", "\n", a - b)
print("Multiplication:", "\n", a * b)

array 1: 
 [4 7 4 8 5]
array 2: 
 [3 3 9 4 2]
Addition: 
 [ 7 10 13 12  7]
Subtraction: 
 [ 1  4 -5  4  3]
Multiplication: 
 [12 21 36 32 10]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [ ]:
a = np.random.randint(1, 100, size=(7), dtype=int)
print("array 1:", "\n", a)
b = np.random.randint(1, 100, size=(7), dtype=int)
print("array 2:", "\n", b)
print("scalar addition:", "\n", np.dot(a,b))

array 1: 
 [60 76 68 33 72 43 33]
array 2: 
 [70 17 69 57 47 33 74]
scalar addition: 
 19310


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [4]:
a = np.random.randint(1, 10, (2,2), dtype=int)
print("matrix 1:", "\n", a)
b = np.random.randint(1, 10, (2,3), dtype=int)
print("matrix 2:", "\n", b)
print("result:", "\n", np.dot(a,b))

matrix 1: 
 [[3 4]
 [4 6]]
matrix 2: 
 [[5 5 8]
 [6 8 1]]
result: 
 [[39 47 28]
 [56 68 38]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю

In [ ]:
a = np.random.randint(1, 10, (3,3), dtype=int)
print("matrix:", "\n", a)
b = np.linalg.inv(a)
print("inverse matrix:", "\n", b)

matrix: 
 [[2 4 8]
 [9 5 9]
 [4 9 3]]
inverse matrix: 
 [[-0.16836735  0.15306122 -0.01020408]
 [ 0.02295918 -0.06632653  0.1377551 ]
 [ 0.15561224 -0.00510204 -0.06632653]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її

In [ ]:
a = np.random.random((4, 4))
print("matrix:", "\n", a)
b = a.T
print("transposed matrix:", "\n", b)

matrix: 
 [[0.56661375 0.48351078 0.94805271 0.67741893]
 [0.53873906 0.09529404 0.71753269 0.42774675]
 [0.69757473 0.50746867 0.84472519 0.14485289]
 [0.19756801 0.56038425 0.87329155 0.87660856]]
transposed matrix: 
 [[0.56661375 0.53873906 0.69757473 0.19756801]
 [0.48351078 0.09529404 0.50746867 0.56038425]
 [0.94805271 0.71753269 0.84472519 0.87329155]
 [0.67741893 0.42774675 0.14485289 0.87660856]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор

In [5]:
a = np.random.randint(1, 10, (3,4), dtype=int)
print("matrix:", "\n", a)
b = np.random.randint(1, 10, (4), dtype=int)
print("array:", "\n", b)
print("result:", "\n", np.dot(a,b))

matrix: 
 [[5 8 7 9]
 [9 2 6 9]
 [3 2 6 9]]
array: 
 [2 8 2 2]
result: 
 [106  64  52]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор

In [6]:
a = np.random.random((2, 3))
print("matrix:", "\n", a)
b = np.random.random((3))
print("array:", "\n", b)
print("result:", "\n", np.dot(a,b))

matrix: 
 [[0.15772619 0.05334531 0.58111006]
 [0.77781896 0.95472162 0.87234532]]
array: 
 [0.54325602 0.59713314 0.22117413]
result: 
 [0.24606647 1.18559096]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення

In [7]:
a = np.random.randint(1, 10, (2,2), dtype=int)
print("matrix 1:", "\n", a)
b = np.random.randint(1, 10, (2,2), dtype=int)
print("matrix 2:", "\n", b)
print("result:", "\n", a * b)

matrix 1: 
 [[8 2]
 [7 5]]
matrix 2: 
 [[6 9]
 [4 4]]
result: 
 [[48 18]
 [28 20]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток

In [8]:
a = np.random.randint(1, 10, (2,2), dtype=int)
print("matrix 1:", "\n", a)
b = np.random.randint(1, 10, (2,2), dtype=int)
print("matrix 2:", "\n", b)
print("result:", "\n", a + b)

matrix 1: 
 [[3 2]
 [2 4]]
matrix 2: 
 [[2 4]
 [7 5]]
result: 
 [[5 6]
 [9 9]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці

In [ ]:
a = np.random.randint(1, 100, (5,5), dtype=int)
print("matrix:", "\n", a)
print("sum: ", a.sum())

matrix: 
 [[26 51 69 91 87]
 [16 48 52 19 89]
 [41 22  1 35 96]
 [47 72 49  9 19]
 [37 87 44 29 80]]
sum:  1216


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю

In [9]:
a = np.random.randint(1, 10, (4,4), dtype=int)
print("matrix 1:", "\n", a)
b = np.random.randint(1, 10, (4,4), dtype=int)
print("matrix 2:", "\n", b)
print("result:", "\n", a - b)

matrix 1: 
 [[6 3 4 3]
 [8 5 3 1]
 [8 6 6 3]
 [7 9 6 5]]
matrix 2: 
 [[9 3 6 2]
 [9 6 8 4]
 [2 8 4 6]
 [6 4 9 8]]
result: 
 [[-3  0 -2  1]
 [-1 -1 -5 -3]
 [ 6 -2  2 -3]
 [ 1  5 -3 -3]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці

In [ ]:
a = np.random.random((3, 3))
print("matrix:", "\n", a)
print("result:", "\n", a.sum(axis=1))

matrix: 
 [[0.61330896 0.51850077 0.47919775]
 [0.61078741 0.12984433 0.30467614]
 [0.3930817  0.17033602 0.23899513]]
result: 
 [1.61100748 1.04530788 0.80241285]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел

In [10]:
a = np.random.randint(1, 100, size=(3,4), dtype=int)
print("matrix:", "\n", a)
print("result:", "\n", np.power(a, 2))

matrix: 
 [[93  4 16 58]
 [47 42 29  5]
 [36  1 92 22]]
result: 
 [[8649   16  256 3364]
 [2209 1764  841   25]
 [1296    1 8464  484]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел

In [11]:
a = np.random.randint(1, 50, size=(4), dtype=int)
print("array:", "\n", a)
print("result:", "\n", np.sqrt(a))

array: 
 [32  6 49 42]
result: 
 [5.65685425 2.44948974 7.         6.4807407 ]
